# Generated by Django 5.2.13 on 2026-04-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCash', '0002_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='profileimage',
            field=models.ImageField(null=True, upload_to='Media_file'),
        ),
    ]
